name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt-get install -y libboost1.65-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake $GITHUB_WORKSPACE -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest -C Release

      - name: Package
        run: |
          cd ${{github.workspace}}/build
          cpack --config CPackConfig.cmake